steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-central2-docker.pkg.dev/$PROJECT_ID/primaria/app:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-central2-docker.pkg.dev/$PROJECT_ID/primaria/app:$COMMIT_SHA']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'primaria'
      - '--image'
      - 'europe-central2-docker.pkg.dev/$PROJECT_ID/primaria/app:$COMMIT_SHA'
      - '--region'
      - 'europe-central2'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--set-secrets'
      - 'DATABASE_URL=primaria-database-url:latest,DIRECT_DATABASE_URL=primaria-direct-database-url:latest,NEXTAUTH_SECRET=primaria-nextauth-secret:latest,STRIPE_SECRET_KEY=primaria-stripe-key:latest,STRIPE_WEBHOOK_SECRET=primaria-stripe-webhook:latest,AI_GATEWAY_URL=primaria-ai-gateway-url:latest,AI_GATEWAY_KEY=primaria-ai-gateway-key:latest'
images:
  - 'europe-central2-docker.pkg.dev/$PROJECT_ID/primaria/app:$COMMIT_SHA'
